apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: github-build-
spec:
  entrypoint: build-workflow
  volumes:
  - name: workdir
    emptyDir: {}
  templates:
  - name: build-workflow
    steps:
    - - name: clone-repo
        template: clone-repo

  - name: clone-repo
    container:
      image: golang:1.22
      command: [sh, -c]
      args: [
        "echo 'Cloning repository...' && \
        git clone https://github.com/tbpatil/ArgoPlay.git && \
        echo 'Repository cloned. Listing contents:' && \
        ls -R && \
        cd ArgoPlay && \
        make"
      ]
      volumeMounts:
      - name: workdir
        mountPath: /ArgoPlay

